# Generated by Django 5.0.4 on 2024-05-20 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saudacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saudacaoNoiva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saudacaoNoiva', to='core.noiva')),
                ('saudacaoNoivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saudacaoNoivo', to='core.noivo')),
            ],
            options={
                'verbose_name': 'Saudação',
                'verbose_name_plural': 'Saudações',
            },
        ),
    ]
