# Generated by Django 5.0.4 on 2024-05-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casamento',
            fields=[
                ('noivo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.noivo')),
                ('dataCerimonia', models.DateField(verbose_name='Data da Cerimonia')),
            ],
            options={
                'verbose_name': 'Casamento',
                'verbose_name_plural': 'Casamentos',
            },
            bases=('core.noivo',),
        ),
    ]
