# Generated by Django 5.0.4 on 2024-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='tipo',
            field=models.CharField(choices=[('convidado', 'convidado'), ('padrinho', 'padrinho'), ('noivo', 'noivo'), ('noiva', 'noiva')], max_length=9, verbose_name='Tipo'),
        ),
    ]
