# Generated by Django 5.0.4 on 2024-04-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_people_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='bio',
        ),
        migrations.AlterField(
            model_name='people',
            name='tipo',
            field=models.CharField(choices=[('convidado', 'convidado'), ('padrinho', 'padrinho')], max_length=9, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.people')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.people',),
        ),
    ]
