# Generated by Django 5.0.4 on 2024-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saudacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='saudacao',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
