# Generated by Django 5.0.4 on 2024-05-21 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_saudacao_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noivo',
            name='noiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noivo', to='core.noiva'),
        ),
    ]
