# Generated by Django 5.0.4 on 2024-04-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_people_bio_alter_people_tipo_noivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='tipo',
            field=models.CharField(choices=[('convidado', 'convidado'), ('padrinho', 'padrinho'), ('noivo', 'noivo'), ('noiva', 'noiva')], max_length=9, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Noivo',
        ),
    ]
