# Generated by Django 5.0.4 on 2024-04-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_people_tipo_delete_noivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.people')),
                ('bio', models.TextField(max_length=200, verbose_name='Bio')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.people',),
        ),
        migrations.RemoveField(
            model_name='people',
            name='tipo',
        ),
    ]
