# Generated by Django 5.0.4 on 2024-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_noiva_noivo_alter_noivo_noiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='casamento',
            name='mensagemPadrinhos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
