# Generated by Django 5.0.4 on 2024-05-21 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_casamento_mensagempadrinhos'),
    ]

    operations = [
        migrations.AddField(
            model_name='casamento',
            name='horaInicio',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AddField(
            model_name='casamento',
            name='horaTermino',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
    ]
