# Generated by Django 5.0.4 on 2024-04-17 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_noiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrinho',
            fields=[
                ('people_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.people')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.people',),
        ),
    ]
