# Generated by Django 5.0.4 on 2024-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_padrinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noivo',
            name='people_ptr',
        ),
        migrations.RemoveField(
            model_name='padrinho',
            name='people_ptr',
        ),
        migrations.DeleteModel(
            name='Noiva',
        ),
        migrations.DeleteModel(
            name='Noivo',
        ),
        migrations.DeleteModel(
            name='Padrinho',
        ),
        migrations.DeleteModel(
            name='People',
        ),
    ]
