# Generated by Django 5.0.4 on 2024-05-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_casamento_horainicio_casamento_horatermino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casamento',
            old_name='horaInicio',
            new_name='horaInicioCerimonia',
        ),
        migrations.RenameField(
            model_name='casamento',
            old_name='horaTermino',
            new_name='horaTerminoFesta',
        ),
    ]
