# Generated by Django 5.0.4 on 2024-05-21 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_horainicio_casamento_horainiciocerimonia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casamento',
            name='horaInicioFesta',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
        migrations.AddField(
            model_name='casamento',
            name='horaTerminoCerimonia',
            field=models.TimeField(blank=True, default=datetime.time(12, 0), null=True),
        ),
    ]
