# Generated by Django 5.0.4 on 2024-04-18 13:59

import core.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('bio', models.TextField(max_length=200, verbose_name='bio')),
            ],
            options={
                'verbose_name': 'Noiva',
                'verbose_name_plural': 'Noivas',
            },
        ),
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('noiva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.noiva')),
            ],
            options={
                'verbose_name': 'Noivo',
                'verbose_name_plural': 'Noivos',
            },
            bases=('core.noiva',),
        ),
    ]
