# Generated by Django 5.0.4 on 2024-05-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_casamento_horainiciofesta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casamento',
            old_name='mensagemPadrinhos',
            new_name='mensagemCerimonia',
        ),
        migrations.AddField(
            model_name='casamento',
            name='mensagemFesta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
