# Generated by Django 5.0.4 on 2024-04-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_noiva_noivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noiva',
            name='bio',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Noivo',
        ),
    ]
