# Generated by Django 5.0.4 on 2024-04-18 14:33

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_noiva_bio_delete_noivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem')),
                ('facebook', models.CharField(default='#', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=100, verbose_name='Instagram')),
                ('descricao', models.TextField(default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Noivo',
                'verbose_name_plural': 'Noivos',
            },
        ),
    ]
