# Generated by Django 5.0.4 on 2024-05-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_nossoblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='casamento',
            name='textoApresentacaoBlog',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
