# Generated by Django 5.0.4 on 2024-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_descricao_noivo_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrinho',
            name='ladoFamilia',
        ),
        migrations.AddField(
            model_name='padrinho',
            name='genero',
            field=models.CharField(choices=[('padrinho', 'padrinho'), ('madrinha', 'madrinha')], default=2, max_length=10, verbose_name='ladoFamilia'),
            preserve_default=False,
        ),
    ]
