# Generated by Django 5.0.4 on 2024-04-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_descricao_noivo_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrinho',
            name='ladoFamilia',
        ),
    ]
