# Generated by Django 5.0.4 on 2024-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_padrinho_ladofamilia'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrinho',
            name='genero',
            field=models.CharField(choices=[('padrinho', 'padrinho'), ('madrinha', 'madrinha')], default='padrinho', max_length=10, verbose_name='genero'),
        ),
    ]
