# Generated by Django 5.0.6 on 2024-06-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
