# Generated by Django 5.0.4 on 2024-04-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_padrinho_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padrinho',
            name='genero',
            field=models.CharField(choices=[('padrinho', 'padrinho'), ('madrinha', 'madrinha')], default=None, max_length=10, null=True, verbose_name='gênero'),
        ),
    ]
